LIBS += $(LIB)

UTILLIB := $(LIB)
UTILDIR := $(DIR)
OBJS :=

include $(UTILDIR)system/makefile
include $(UTILDIR)kin/makefile
include $(UTILDIR)diag/makefile
include $(UTILDIR)univariate/makefile
include $(UTILDIR)cuba/makefile
include $(UTILDIR)ode/makefile
include $(UTILDIR)qcd/makefile
include $(UTILDIR)ninja/makefile
include $(UTILDIR)samurai/makefile
include $(UTILDIR)cuttools/makefile
include $(UTILDIR)compaz/makefile

$(UTILLIB): $(UTILLIB)($(OBJS))

