#! /bin/sh
# a trivial utility for getting the data out of the logs
# this file is part of FormCalc
# last modified 26 Jan 18 th


test $# -eq 0 && {
  cat << _EOF_
Usage:  $0 dir1 dir2 ...

Extracts the data from the log files dir1/*, dir2/*, ...
and writes them to the respective files dir1.data, dir2.data, ...

_EOF_
  exit 1
}

for dir in "$@" ; do
  test -d "$dir" || {
    echo "$dir is no directory"
    continue
  }
  d=`dirname "$dir/x"`
  echo "$d"
  sed -n '
	s/^|//
	t 1
	b
	: 1
	N
	s/\n|+//
	t 1
	P
	D' "$d"/* > "$d.data"
done

