#! /bin/sh
# a trivial utility for getting the data out of the logs
# this file is part of FormCalc
# last modified 16 Oct 15 th


test $# -eq 0 && {
  cat << _EOF_
Usage:  $0 dir1 dir2 ...

Extracts the data from the log files dir1/*, dir2/*, ...
and writes them to the respective files dir1.data, dir2.data, ...

_EOF_
  exit 1
}

files=""
out=""
for arg in "$@" ; do
  arg=`dirname "$arg"/*`
  echo "$arg"
  sed -n '
	s/^|//
	t 1
	b
	: 1
	N
	s/\n|+//
	t 1
	P
	D' "$arg"/* > "$arg.data"
done
