#! /bin/sh
# script to compile C programs that are linked 
# against Fortran libraries
# last modified 13 Jan 09 th

args=""
ldflags=""
libs=""
compileonly=""

case "$@" in
*-m32*)	toarg='arg=`echo "$1" | sed -e 's/-x86-64//g' -e 's/ML64/ML32/g'`' ;;
*)	toarg='arg=$1' ;;
esac

while [ $# -gt 0 ] ; do
  eval "$toarg"
  case "$arg" in
  -arch)
	shift
	;;
  -[Ll]* | -Wl* | *.a)
	ldflags="$ldflags \"$arg\""
	;;
  -Wno-long-double)
	# mcc adds this on Macs & gcc 4 doesn't like it
	;;
  *.cc)
	args="$args \"$arg\""
	libs="-lstdc++ $libs"
	;;
  -c)
	compileonly="-c"
	;;
  *)
	args="$args \"$arg\""
	;;
  esac
  shift
done

eval "set -x ; ${REALCC:-cc} $args ${compileonly:-$ldflags $libs}"

