#! /bin/sh
# download the FORM executables
# invoke as "getform t" to download tform instead of form
# last modified 20 Mar 09 th

download()
{
  wget http://www.nikhef.nl/~form/maindir/binaries/$1
  mv -f `basename $1` $2.gz
  gunzip $2.gz
  chmod 755 $2
}

download linux32/$1form.gz form_Linux
download opteron/$1form.gz form_Linux-x86-64
download ppc/$1form.gz form_MacOSX
ln -s form_MacOSX form_Darwin
download apentium/$1form.gz form_MacOSX-x86
ln -s form_MacOSX-x86 form_MacOSX-x86-64

