#! /bin/sh -x
# get and build FORM for a given platform
# last modified 31 Mar 15 th

gmp=gmp-5.1.3
zlib=zlib-1.2.8

cc=gcc
cxx=g++
clang --version > /dev/null 2>&1 && {
  cc=clang
  cxx=clang++
}

cflags="-O3 -fomit-frame-pointer"
lin_cflags="$cflags -static"
mac_cflags="$cflags -fno-pic -mmacosx-version-min=10.6 -stdlib=libstdc++"
win_cflags="$cflags"
ldflags=
exe=

case "$1" in
Linux)
	build=i686-unknown-linux-gnu
	cc=gcc
	cxx=g++
	cflags="$lin_cflags -m32"
	;;
Linux-x86-64)
	build=x86_64-unknown-linux-gnu
	cflags="$lin_cflags"
	;;
MacOSX-x86)
	build=i486-apple-darwin
	cflags="$mac_cflags -m32 -Wl,-read_only_relocs,suppress"
	ldflags="-Wl,-no_pie"
	;;
MacOSX-x86-64)
	build=x86_64-apple-darwin
	cflags="$mac_cflags"
	ldflags="-Wl,-no_pie"
	;;
Windows)
	build=i686-pc-cygwin
	cc=$build-gcc
	cxx=$build-g++
	cflags="$win_cflags"
	exe=.exe
	;;
Windows-x86-64)
	build=x86_64-pc-cygwin
	cc=$build-gcc
	cxx=$build-g++
	cflags="$win_cflags"
	exe=.exe
	;;
*)
	cat << _EOF_
Usage: $0 platform
where platform is one of
Linux
Linux-x86-64
MacOSX-x86
MacOSX-x86-64
Windows
Windows-x86-64
_EOF_
	exit 1
	;;
esac


src="$PWD"
dest=/tmp/makeform-build
rm -fr $dest
mkdir $dest
mv -f $1 $dest/
cp -pf $gmp.tar.gz $zlib.tar.gz form-master.zip $dest/
trap "mv '$dest/$1' '$src'" 0 1 2 3 15
cd $dest

make BUILD="$build" \
     SRC="$src" \
     DEST="$dest/$1" \
     CC="$cc" \
     CXX="$cxx" \
     CFLAGS="$cflags" \
     LDFLAGS="$ldflags" \
     EXE="$exe" \
     GMP="$gmp" \
     ZLIB="$zlib" -f - << \_EOF_

CONF1 = \
CC="$(CC)" CFLAGS="$(CFLAGS)" \
CXX="$(CXX)" CXXFLAGS="$(CFLAGS)" \
LDFLAGS="$(LDFLAGS)" \
./configure --prefix=$(DEST)

CONF2 = $(CONF1) --build="$(BUILD)"

form-master/sources/tform: $(DEST)/lib/libgmp.a $(DEST)/lib/libz.a form-master.zip
	unzip form-master.zip
	sed -i \
	  -e '/mmacosx-version-min/d' \
	  -e '/LINKFLAGS/s/-s//' form-master/sources/Makefile.am
	cd form-master && autoreconf -i
	cd form-master && $(CONF2) --with-gmp=$(DEST) --with-zlib=$(DEST)
	sed -i \
	  -e 's|-lz|"$(DEST)/lib/libz.a"|' \
	  -e 's|-lgmp|"$(DEST)/lib/libgmp.a"|' form-master/sources/Makefile
	cd form-master && $(MAKE) install
	strip $(DEST)/bin/*form$(EXE)
	rm -fr form-master

form-master.zip:
	wget -O form-master.zip https://github.com/vermaseren/form/archive/master.zip
	cp -p form-master.zip "$(SRC)/"

$(DEST)/lib/libgmp.a: $(GMP).tar.gz
	tar xvfz $(GMP).tar.gz
	cd $(GMP) && $(CONF2) --disable-shared
	cd $(GMP) && $(MAKE) install
	rm -fr $(GMP)

$(GMP).tar.gz:
	wget http://ftp.gnu.org/gnu/gmp/$(GMP).tar.gz
	cp -p $(GMP).tar.gz "$(SRC)/"

$(DEST)/lib/libz.a: $(ZLIB).tar.gz
	tar xvfz $(ZLIB).tar.gz
	cd $(ZLIB) && $(CONF1)
	cd $(ZLIB) && $(MAKE) SHAREDLIBV= install
	rm -fr $(ZLIB)

$(ZLIB).tar.gz:
	wget http://zlib.net/$(ZLIB).tar.gz
	cp -p $(ZLIB).tar.gz "$(SRC)/"

_EOF_

