#! /bin/sh -x
# get and build FORM for a given platform
# last modified 14 Nov 13 th

gmp=gmp-5.1.3
zlib=zlib-1.2.8

cc=clang
cxx=clang++
cflags="-O3 -fomit-frame-pointer"
lin_cflags="$cflags -static"
mac_cflags="$cflags -mmacosx-version-min=10.6"
win_cflags="$cflags"

case "$1" in
Linux)
	build=i686-unknown-linux-gnu
	cc=gcc
	cxx=g++
	cflags="$lin_cflags -m32"
	;;
Linux-x86-64)
	build=x86_64-unknown-linux-gnu
	cflags="$lin_cflags"
	;;
MacOSX-x86)
	build=i486-apple-darwin
	cflags="$mac_cflags -m32"
	;;
MacOSX-x86-64)
	build=x86_64-apple-darwin
	cflags="$mac_cflags"
	;;
Windows)
	build=i686-pc-cygwin
	cc=$build-gcc
	cxx=$build-g++
	cflags="$win_cflags"
	;;
Windows-x86-64)
	build=x86_64-pc-cygwin
	cc=$build-gcc
	cxx=$build-g++
	cflags="$win_cflags"
	;;
*)
	cat << _EOF_
Usage: $0 platform
where platform is one of
Linux
Linux-x86-64
MacOSX-x86
MacOSX-x86-64
Windows
Windows-x86-64
_EOF_
	exit 1
	;;
esac


src="$PWD"
dest=/tmp/makeform-build
rm -fr $dest
mkdir $dest
mv -f $1 $dest/
cp -pf $gmp.tar.gz $zlib.tar.gz formcvs.tar.gz $dest/
trap "mv '$dest/$1' '$src'" 0 1 2 3 15
cd $dest

make BUILD="$build" \
     SRC="$src" \
     DEST="$dest/$1" \
     CC="$cc" \
     CXX="$cxx" \
     CFLAGS="$cflags" \
     GMP="$gmp" \
     ZLIB="$zlib" -f - << \_EOF_

CONF1 = \
CC="$(CC)" CFLAGS="$(CFLAGS)" \
CXX="$(CXX)" CXXFLAGS="$(CFLAGS)" ./configure --prefix=$(DEST)

CONF2 = $(CONF1) --build="$(BUILD)"

formcvs/sources/tform: $(DEST)/lib/libgmp.a $(DEST)/lib/libz.a formcvs.tar.gz
	tar xvfz formcvs.tar.gz
	cd formcvs && autoreconf -i
	cd formcvs && $(CONF2) --with-gmp=$(DEST) --with-zlib=$(DEST)
	sed -i \
	  -e 's|-lz|"$(DEST)/lib/libz.a"|' \
	  -e 's|-lgmp|"$(DEST)/lib/libgmp.a"|' formcvs/sources/Makefile
	cd formcvs && $(MAKE) install
	rm -fr formcvs

formcvs.tar.gz:
	wget -O formcvs.tar.gz 'http://www.nikhef.nl/~form/formcvs.php?dl=formcvs.tar.gz'
	cp -p formcvs.tar.gz "$(SRC)/"

$(DEST)/lib/libgmp.a: $(GMP).tar.gz
	tar xvfz $(GMP).tar.gz
	cd $(GMP) && $(CONF2) --disable-shared
	cd $(GMP) && $(MAKE) install
	rm -fr $(GMP)

$(GMP).tar.gz:
	wget http://ftp.gnu.org/gnu/gmp/$(GMP).tar.gz
	cp -p $(GMP).tar.gz "$(SRC)/"

$(DEST)/lib/libz.a: $(ZLIB).tar.gz
	tar xvfz $(ZLIB).tar.gz
	cd $(ZLIB) && $(CONF1)
	cd $(ZLIB) && $(MAKE) SHAREDLIBV= install
	rm -fr $(ZLIB)

$(ZLIB).tar.gz:
	wget http://zlib.net/$(ZLIB).tar.gz
	cp -p $(ZLIB).tar.gz "$(SRC)/"

_EOF_

