#! /bin/sh -x


runit()
{
  math -run "<< $1.m ; Exit[]"
  cd $1.fortran
  ./configure
  make
  ./run $2 $3
}


process()
{
  echo "======================= $1 ======================="
  base=$1.fortran/run.$2.$3
  [ -f $base/0000001 ] || ( runit "$@" ) >> log.$1 2>&1
  ndiff $base/0000001 $base-0000001
}


process eett-SM    UUUU  00500
process eett-MSSM  UUUU  00500
process eettA-SM   UUUUU 00500

process eeWW-SM    UUUU  00500
process eeWW-SMbgf UUUU  00500
process eeWW-MSSM  UUUU  00500
process eeHH-MSSM  UUUU  01500

process AAtt-SM    UUUU  00500
process AAttA-SM   UUUUU 00500

process AAAA-SM    UUUU  00500
process AAAA-SMbgf UUUU  00500
process WWWW-SM    UUUU  00500
process WWWW-SMbgf UUUU  00500
process ZZZZ-SM    UUUU  00500
process ZZZZ-SMbgf UUUU  00500

